version: '3'

services:
  db:
    image: mariadb:${MYSQL_VERSION}
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - /data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    networks:
      - back

  app:
    image: nextcloud:${NEXTCLOUD_VERSION}
    restart: always
    volumes:
      - /data/nextcloud:/var/www/html
      - /data/apps:/var/www/html/custom_apps
      - /data/config:/var/www/html/config
      - /data/data:/var/www/html/data
    environment:
      - MYSQL_DATABASE
      - MYSQL_HOST
      - MYSQL_USER
      - MYSQL_PASSWORD
      - REDIS_HOST
      - SMTP_HOST
      - SMTP_SECURE
      - SMTP_PORT
      - SMTP_AUTHTYPE
      - SMTP_NAME
      - SMTP_PASSWORD
      - MAIL_FROM_ADDRESS
      - MAIL_DOMAIN
      - NEXTCLOUD_TRUSTED_DOMAINS
      - NEXTCLOUD_ADMIN_USER
      - NEXTCLOUD_ADMIN_PASSWORD
    depends_on:
      - db
      - redis
    networks:
      - back

  redis:
    image: redis:${REDIS_VERSION}
    restart: always
    networks:
      - back

  cron:
    image: nextcloud:${NEXTCLOUD_VERSION}
    restart: always
    volumes:
      - /data/nextcloud:/var/www/html
    user: www-data
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
    networks:
      - back

  web:
    image: nginx:${NGINX_VERSION}
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /data/nextcloud:/var/www/html:ro
    depends_on:
      - app
    ports:
      - 127.0.0.1:80:80
    networks:
      - back

networks:
  back:
